// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVTdof41DOa-IzgBVyTIdj8rSWS1k7QjU',
    appId: '1:30123225184:web:0358260780aead7a045305',
    messagingSenderId: '30123225184',
    projectId: 'bd-physicians',
    authDomain: 'bd-physicians.firebaseapp.com',
    storageBucket: 'bd-physicians.appspot.com',
    measurementId: 'G-V5D3HBEHLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpYHsqw1XPaSRue01pyhdotgBuGBZ0OSg',
    appId: '1:30123225184:android:535607336b768af3045305',
    messagingSenderId: '30123225184',
    projectId: 'bd-physicians',
    storageBucket: 'bd-physicians.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_S0QJG2upjQG1MGgl5GrxaEcSJXB0jS0',
    appId: '1:30123225184:ios:de608a762319fd62045305',
    messagingSenderId: '30123225184',
    projectId: 'bd-physicians',
    storageBucket: 'bd-physicians.appspot.com',
    iosClientId: '30123225184-9785gev8fq9bd60m3pk6r7tb0jorb4mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.bdphysicians',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_S0QJG2upjQG1MGgl5GrxaEcSJXB0jS0',
    appId: '1:30123225184:ios:de608a762319fd62045305',
    messagingSenderId: '30123225184',
    projectId: 'bd-physicians',
    storageBucket: 'bd-physicians.appspot.com',
    iosClientId: '30123225184-9785gev8fq9bd60m3pk6r7tb0jorb4mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.bdphysicians',
  );
}
